spring.application.name=Backend
spring.mongodb.uri=${MDB_URL}

spring.datasource.url=${PG_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET}

spring.jpa.open-in-view=false

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG